// Code generated by ./extract from github.com/containerd/nerdctl/v2@v2.1.2; DO NOT EDIT.

//go:build linux

package main

import (
	"github.com/spf13/cobra"

	"github.com/containerd/nerdctl/v2/cmd/nerdctl/apparmor"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/builder"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/compose"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/container"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/image"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/inspect"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/ipfs"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/login"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/namespace"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/network"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/system"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/volume"
)

// addExtractedCommands adds every subcommand that nerdctl's newApp adds.
func addExtractedCommands(rootCmd *cobra.Command) {
	rootCmd.AddCommand(
		container.CreateCommand(),
		container.RunCommand(),
		container.UpdateCommand(),
		container.ExecCommand(),
		container.PsCommand(),
		container.LogsCommand(),
		container.PortCommand(),
		container.StopCommand(),
		container.StartCommand(),
		container.DiffCommand(),
		container.RestartCommand(),
		container.KillCommand(),
		container.RemoveCommand(),
		container.PauseCommand(),
		container.UnpauseCommand(),
		container.CommitCommand(),
		container.WaitCommand(),
		container.RenameCommand(),
		container.AttachCommand(),
		builder.BuildCommand(),
		image.ImagesCommand(),
		image.PullCommand(),
		image.PushCommand(),
		image.LoadCommand(),
		image.SaveCommand(),
		image.TagCommand(),
		image.RmiCommand(),
		image.HistoryCommand(),
		system.EventsCommand(),
		system.InfoCommand(),
		inspect.Command(),
		container.TopCommand(),
		container.StatsCommand(),
		container.Command(),
		image.Command(),
		network.Command(),
		volume.Command(),
		system.Command(),
		namespace.Command(),
		builder.Command(),
		login.Command(),
		login.LogoutCommand(),
		compose.Command(),
		ipfs.NewIPFSCommand(),
		apparmor.Command(),
	)
	container.AddCpCommand(rootCmd)
}

// unresolvedCommands are package-main constructors that replica.go provides.
var unresolvedCommands = []string{"versionCommand"}

// skippedCommands are constructors in internal packages; their commands
// stay out of the table and pass through the parser unmodified.
var skippedCommands = []string{"internal.Command"}
