// Code generated by ./extract from github.com/containerd/nerdctl/v2@v2.0.3; DO NOT EDIT.

//go:build linux

package main

import (
	"github.com/spf13/cobra"

	"github.com/containerd/nerdctl/v2/cmd/nerdctl/apparmor"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/builder"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/compose"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/container"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/image"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/inspect"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/ipfs"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/login"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/namespace"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/network"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/system"
	"github.com/containerd/nerdctl/v2/cmd/nerdctl/volume"
)

// addExtractedCommands adds every subcommand that nerdctl's newApp adds.
func addExtractedCommands(rootCmd *cobra.Command) {
	rootCmd.AddCommand(
		container.NewCreateCommand(),
		container.NewRunCommand(),
		container.NewUpdateCommand(),
		container.NewExecCommand(),
		container.NewPsCommand(),
		container.NewLogsCommand(),
		container.NewPortCommand(),
		container.NewStopCommand(),
		container.NewStartCommand(),
		container.NewDiffCommand(),
		container.NewRestartCommand(),
		container.NewKillCommand(),
		container.NewRmCommand(),
		container.NewPauseCommand(),
		container.NewUnpauseCommand(),
		container.NewCommitCommand(),
		container.NewWaitCommand(),
		container.NewRenameCommand(),
		container.NewAttachCommand(),
		builder.NewBuildCommand(),
		image.NewImagesCommand(),
		image.NewPullCommand(),
		image.NewPushCommand(),
		image.NewLoadCommand(),
		image.NewSaveCommand(),
		image.NewTagCommand(),
		image.NewRmiCommand(),
		image.NewHistoryCommand(),
		system.NewEventsCommand(),
		system.NewInfoCommand(),
		inspect.NewInspectCommand(),
		container.NewTopCommand(),
		container.NewStatsCommand(),
		container.NewContainerCommand(),
		image.NewImageCommand(),
		network.NewNetworkCommand(),
		volume.NewVolumeCommand(),
		system.NewSystemCommand(),
		namespace.NewNamespaceCommand(),
		builder.NewBuilderCommand(),
		login.NewLoginCommand(),
		login.NewLogoutCommand(),
		compose.NewComposeCommand(),
		ipfs.NewIPFSCommand(),
		apparmor.NewApparmorCommand(),
	)
	container.AddCpCommand(rootCmd)
}

// unresolvedCommands are package-main constructors that replica.go provides.
var unresolvedCommands = []string{"newVersionCommand"}

// skippedCommands are constructors in internal packages; their commands
// stay out of the table and pass through the parser unmodified.
var skippedCommands = []string{"internal.NewInternalCommand"}
