// Code generated by ./extract from github.com/containerd/nerdctl/v2@v2.0.3; DO NOT EDIT.

//go:build linux

package main

// nerdctlPinnedVersion is the module version extract ran against.
const nerdctlPinnedVersion = "v2.0.3"

// expectedRootFlags are the flag names initRootCmdFlags registers;
// replica.go must register exactly these.
var expectedRootFlags = []string{
	"H",
	"a",
	"address",
	"bridge-ip",
	"cgroup-manager",
	"cni-netconfpath",
	"cni-path",
	"data-root",
	"debug",
	"debug-full",
	"experimental",
	"host",
	"host-gateway-ip",
	"hosts-dir",
	"insecure-registry",
	"kube-hide-dupe",
	"n",
	"namespace",
	"snapshotter",
	"storage-driver",
}
