// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ExtensionStatusApplyConfiguration represents a declarative configuration of the ExtensionStatus type for use
// with apply.
//
// ExtensionStatus defines the observed state of Extension.
type ExtensionStatusApplyConfiguration struct {
	// image is the resolved image reference that is actually used,
	// including the tag.  This is mostly useful when spec.image does not
	// contain a tag.
	//
	Image *string `json:"image,omitempty"`
	// metadata is the contents of metadata.json in the extension image.
	// Only available once the extension has been downloaded.
	//
	Metadata *v1.JSON `json:"metadata,omitempty"`
	// ui describes the user interface exposed by this extension. Only
	// valid after the extension has been started.
	//
	UI *ExtensionUIStatusApplyConfiguration `json:"ui,omitempty"`
	// conditions represent the state of the extension.
	//
	// Known condition types include:
	// - "Installed": the extension image has been downloaded, extracted,
	// and had its post-install script (if any) run successfully.
	// - "Started": the extension's containers (if any) have been started.
	// - "Ready": aggregates the overall extension lifecycle state.
	// - "ContainerEngineReady": the container engine can be used.
	//
	// The status of each condition is one of True, False, or Unknown.
	//
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ExtensionStatusApplyConfiguration constructs a declarative configuration of the ExtensionStatus type for use with
// apply.
func ExtensionStatus() *ExtensionStatusApplyConfiguration {
	return &ExtensionStatusApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ExtensionStatusApplyConfiguration) WithImage(value string) *ExtensionStatusApplyConfiguration {
	b.Image = &value
	return b
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *ExtensionStatusApplyConfiguration) WithMetadata(value v1.JSON) *ExtensionStatusApplyConfiguration {
	b.Metadata = &value
	return b
}

// WithUI sets the UI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UI field is set to the value of the last call.
func (b *ExtensionStatusApplyConfiguration) WithUI(value *ExtensionUIStatusApplyConfiguration) *ExtensionStatusApplyConfiguration {
	b.UI = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ExtensionStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ExtensionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
