// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ExtensionSpecApplyConfiguration represents a declarative configuration of the ExtensionSpec type for use
// with apply.
//
// ExtensionSpec defines the desired state of Extension.
type ExtensionSpecApplyConfiguration struct {
	// image is the image reference for the extension. The tag is optional;
	// if omitted, status.image reports the resolved reference (the image
	// with the highest semver tag, or "latest" if none are available).
	//
	// metadata.name must be the sanitized version of this value (excluding
	// the tag); resource creation or update is rejected otherwise.
	//
	Image *string `json:"image,omitempty"`
}

// ExtensionSpecApplyConfiguration constructs a declarative configuration of the ExtensionSpec type for use with
// apply.
func ExtensionSpec() *ExtensionSpecApplyConfiguration {
	return &ExtensionSpecApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ExtensionSpecApplyConfiguration) WithImage(value string) *ExtensionSpecApplyConfiguration {
	b.Image = &value
	return b
}
