// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ExtensionUIStatusApplyConfiguration represents a declarative configuration of the ExtensionUIStatus type for use
// with apply.
//
// ExtensionUIStatus describes the user interface exposed by an extension.
// Only valid after the extension has been started.
type ExtensionUIStatusApplyConfiguration struct {
	// dashboardTab describes the dashboard tab UI exposed by this
	// extension, if any.
	//
	DashboardTab *ExtensionDashboardTabStatusApplyConfiguration `json:"dashboardTab,omitempty"`
}

// ExtensionUIStatusApplyConfiguration constructs a declarative configuration of the ExtensionUIStatus type for use with
// apply.
func ExtensionUIStatus() *ExtensionUIStatusApplyConfiguration {
	return &ExtensionUIStatusApplyConfiguration{}
}

// WithDashboardTab sets the DashboardTab field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DashboardTab field is set to the value of the last call.
func (b *ExtensionUIStatusApplyConfiguration) WithDashboardTab(value *ExtensionDashboardTabStatusApplyConfiguration) *ExtensionUIStatusApplyConfiguration {
	b.DashboardTab = value
	return b
}
