// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ExtensionDashboardTabStatusApplyConfiguration represents a declarative configuration of the ExtensionDashboardTabStatus type for use
// with apply.
//
// ExtensionDashboardTabStatus describes the dashboard tab UI exposed by an
// extension.
type ExtensionDashboardTabStatusApplyConfiguration struct {
	// title is the title to display for this extension in the side bar.
	//
	Title *string `json:"title,omitempty"`
	// src is the initial page to load for this extension; relative to
	// `.../ui/` on the passthrough endpoint for this extension.
	//
	Src *string `json:"src,omitempty"`
	// socket indicates that the UI should set up a loopback TCP listener
	// forwarding to the `.../socket` passthrough endpoint for this
	// extension.
	//
	Socket *bool `json:"socket,omitempty"`
}

// ExtensionDashboardTabStatusApplyConfiguration constructs a declarative configuration of the ExtensionDashboardTabStatus type for use with
// apply.
func ExtensionDashboardTabStatus() *ExtensionDashboardTabStatusApplyConfiguration {
	return &ExtensionDashboardTabStatusApplyConfiguration{}
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *ExtensionDashboardTabStatusApplyConfiguration) WithTitle(value string) *ExtensionDashboardTabStatusApplyConfiguration {
	b.Title = &value
	return b
}

// WithSrc sets the Src field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Src field is set to the value of the last call.
func (b *ExtensionDashboardTabStatusApplyConfiguration) WithSrc(value string) *ExtensionDashboardTabStatusApplyConfiguration {
	b.Src = &value
	return b
}

// WithSocket sets the Socket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Socket field is set to the value of the last call.
func (b *ExtensionDashboardTabStatusApplyConfiguration) WithSocket(value bool) *ExtensionDashboardTabStatusApplyConfiguration {
	b.Socket = &value
	return b
}
