// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ConfigMapSpecApplyConfiguration represents a declarative configuration of the ConfigMapSpec type for use
// with apply.
//
// ConfigMapSpec defines the desired state of ConfigMapReplicaSet.
// This spec allows users to specify how many ConfigMaps should be created
// and what data they should contain.
type ConfigMapSpecApplyConfiguration struct {
	// Data contains the key-value pairs that will be stored in each ConfigMap.
	// This data is replicated across all managed ConfigMaps with an additional
	// "index" field added to distinguish each replica.
	Data map[string]string `json:"data,omitempty"`
	// Replicas specifies the desired number of ConfigMaps to maintain.
	// The controller will create, update, or delete ConfigMaps to match this count.
	// If not specified, defaults to 1.
	Replicas *int32 `json:"replicas,omitempty"`
}

// ConfigMapSpecApplyConfiguration constructs a declarative configuration of the ConfigMapSpec type for use with
// apply.
func ConfigMapSpec() *ConfigMapSpecApplyConfiguration {
	return &ConfigMapSpecApplyConfiguration{}
}

// WithData puts the entries into the Data field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Data field,
// overwriting an existing map entries in Data field with the same key.
func (b *ConfigMapSpecApplyConfiguration) WithData(entries map[string]string) *ConfigMapSpecApplyConfiguration {
	if b.Data == nil && len(entries) > 0 {
		b.Data = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Data[k] = v
	}
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ConfigMapSpecApplyConfiguration) WithReplicas(value int32) *ConfigMapSpecApplyConfiguration {
	b.Replicas = &value
	return b
}
