// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NotarySpecApplyConfiguration represents a declarative configuration of the NotarySpec type for use
// with apply.
//
// NotarySpec defines the desired state of Notary.
type NotarySpecApplyConfiguration struct {
	// Value is the field that will be tracked for changes
	Value *string `json:"value,omitempty"`
	// ConfigMapName is the name of the ConfigMap where the history will be stored
	ConfigMapName *string `json:"configMapName,omitempty"`
}

// NotarySpecApplyConfiguration constructs a declarative configuration of the NotarySpec type for use with
// apply.
func NotarySpec() *NotarySpecApplyConfiguration {
	return &NotarySpecApplyConfiguration{}
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *NotarySpecApplyConfiguration) WithValue(value string) *NotarySpecApplyConfiguration {
	b.Value = &value
	return b
}

// WithConfigMapName sets the ConfigMapName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMapName field is set to the value of the last call.
func (b *NotarySpecApplyConfiguration) WithConfigMapName(value string) *NotarySpecApplyConfiguration {
	b.ConfigMapName = &value
	return b
}
