// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TemplateReferenceApplyConfiguration represents a declarative configuration of the TemplateReference type for use
// with apply.
//
// TemplateReference specifies a reference to a ConfigMap containing a VM template.
type TemplateReferenceApplyConfiguration struct {
	// name is the name of the ConfigMap containing the VM template.
	// The ConfigMap must have a "template" key.
	Name *string `json:"name,omitempty"`
	// namespace is the namespace of the ConfigMap.
	// If not specified, defaults to the namespace of the LimaVM resource.
	Namespace *string `json:"namespace,omitempty"`
}

// TemplateReferenceApplyConfiguration constructs a declarative configuration of the TemplateReference type for use with
// apply.
func TemplateReference() *TemplateReferenceApplyConfiguration {
	return &TemplateReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TemplateReferenceApplyConfiguration) WithName(value string) *TemplateReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *TemplateReferenceApplyConfiguration) WithNamespace(value string) *TemplateReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}
