// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/lima/v1alpha1"
	internal "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/lima/v1alpha1/applyconfiguration/internal"
	limav1alpha1 "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/lima/v1alpha1/applyconfiguration/lima/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=lima.rancherdesktop.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("LimaVM"):
		return &limav1alpha1.LimaVMApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("LimaVMSpec"):
		return &limav1alpha1.LimaVMSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("LimaVMStatus"):
		return &limav1alpha1.LimaVMStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TemplateReference"):
		return &limav1alpha1.TemplateReferenceApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
