// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	containersv1alpha1 "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/containers/v1alpha1"
)

// ContainerSpecApplyConfiguration represents a declarative configuration of the ContainerSpec type for use
// with apply.
//
// ContainerSpec defines the configuration the container was created with.
type ContainerSpecApplyConfiguration struct {
	// State is the desired state of the container. Valid values are
	// "unknown", "created", and "running". The engine controller creates
	// every Container mirror with state=unknown, meaning "mirror Docker
	// container status but take no start/stop action". Setting the
	// field to "running" or "created" expresses user intent: the
	// reconciler then dispatches ContainerStart, ContainerUnpause, or
	// ContainerStop as needed until the container reaches the
	// corresponding observed state. "created" is satisfied by any
	// non-running state (created, exited, dead).
	State *containersv1alpha1.ContainerStatusValue `json:"state,omitempty"`
}

// ContainerSpecApplyConfiguration constructs a declarative configuration of the ContainerSpec type for use with
// apply.
func ContainerSpec() *ContainerSpecApplyConfiguration {
	return &ContainerSpecApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *ContainerSpecApplyConfiguration) WithState(value containersv1alpha1.ContainerStatusValue) *ContainerSpecApplyConfiguration {
	b.State = &value
	return b
}
