// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ContainerPortApplyConfiguration represents a declarative configuration of the ContainerPort type for use
// with apply.
//
// ContainerPort defines a single exposed port in a container.
type ContainerPortApplyConfiguration struct {
	// Name of the port; in the form [port]/[protocol], e.g. "80/tcp".
	Name *string `json:"name,omitempty"`
	// Bindings to the host port; empty for an exposed but unpublished port,
	// otherwise one entry per binding (e.g. IPv4 and IPv6).
	Bindings []ContainerPortBindingApplyConfiguration `json:"bindings,omitempty"`
}

// ContainerPortApplyConfiguration constructs a declarative configuration of the ContainerPort type for use with
// apply.
func ContainerPort() *ContainerPortApplyConfiguration {
	return &ContainerPortApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ContainerPortApplyConfiguration) WithName(value string) *ContainerPortApplyConfiguration {
	b.Name = &value
	return b
}

// WithBindings adds the given value to the Bindings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Bindings field.
func (b *ContainerPortApplyConfiguration) WithBindings(values ...*ContainerPortBindingApplyConfiguration) *ContainerPortApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBindings")
		}
		b.Bindings = append(b.Bindings, *values[i])
	}
	return b
}
