// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/rdd/v1alpha1"
	internal "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/rdd/v1alpha1/applyconfiguration/internal"
	rddv1alpha1 "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/rdd/v1alpha1/applyconfiguration/rdd/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=rdd.rancherdesktop.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("ConfigMapReplicaSet"):
		return &rddv1alpha1.ConfigMapReplicaSetApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConfigMapSpec"):
		return &rddv1alpha1.ConfigMapSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConfigMapStatus"):
		return &rddv1alpha1.ConfigMapStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Notary"):
		return &rddv1alpha1.NotaryApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NotarySpec"):
		return &rddv1alpha1.NotarySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NotaryStatus"):
		return &rddv1alpha1.NotaryStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
