#!/bin/bash

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: SUSE LLC
# SPDX-FileCopyrightText: The Rancher Desktop Authors

set -o errexit -o nounset

API_GROUPS=$(
	cd pkg/apis
	# shellcheck disable=SC2012
	ls -d -- */ | tr -d /
)

TMPDIR=$(mktemp -d)
readonly TMPDIR
trap 'rm -rf "$TMPDIR"' EXIT

cat > "$TMPDIR/header.txt" <<EOF
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: SUSE LLC
# SPDX-FileCopyrightText: The Rancher Desktop Authors
# Generated by generate-crds.sh; DO NOT EDIT.
EOF

for apigroup in $API_GROUPS; do
	# Generate all CRDs for this API group to temp directory
	go tool controller-gen "crd:headerFile=$TMPDIR/header.txt" "paths=./pkg/apis/${apigroup}/..." "output:crd:dir=${TMPDIR}"

	# Distribute CRDs to their respective controller directories
	for controller_dir in "pkg/controllers/${apigroup}"/*/; do
		if [ -f "$controller_dir/crd.yaml" ]; then
			controller=$(basename "$controller_dir")
			crd_file=$(grep --ignore-case --files-with-matches "^ *kind: ${controller}$" "$TMPDIR"/*.yaml || :)
			if [[ -n $crd_file ]] && [[ -f $crd_file ]]; then
				mv "$crd_file" "${controller_dir}/crd.yaml"
			else
			  echo "Could not locate CRD for ${controller}"
			  exit 1
			fi
		fi
	done
done
