#!/bin/bash

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: SUSE LLC
# SPDX-FileCopyrightText: The Rancher Desktop Authors

set -o errexit -o nounset

API_GROUPS=$(
	cd pkg/apis
	# shellcheck disable=SC2012
	ls -d -- */ | tr -d /
)

TMPDIR=$(mktemp -d)
readonly TMPDIR
trap 'rm -rf "$TMPDIR"' EXIT

cat > "$TMPDIR/header.txt" <<EOF
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: SUSE LLC
# SPDX-FileCopyrightText: The Rancher Desktop Authors
# Generated by generate-crds.sh; DO NOT EDIT.
EOF

for apigroup in $API_GROUPS; do
	# Generate all CRDs for this API group to temp directory
	rm -f "$TMPDIR"/*.yaml
	go tool controller-gen "crd" "paths=./pkg/apis/${apigroup}/..." "output:crd:dir=${TMPDIR}"

	# Concatenate CRDs into their respective controller directories
	for crd_path in "$TMPDIR"/*.yaml; do
		kind=$(yq '.metadata.annotations."rdd.rancherdesktop.io/controller" // .spec.names.singular' < "$crd_path")
		out_path="pkg/controllers/${apigroup}/${kind}/crd.yaml"
		mock_path="pkg/controllers/mock/crd.yaml"

		# Clear the output crd.yaml file if this is the first time we're seeing
		# this kind in this apigroup.
		flag_var="SEEN_${apigroup}_${kind}"
		if [ -z "${!flag_var:-}" ]; then
			cp "$TMPDIR/header.txt" "$out_path"
			eval "${flag_var}=true"
		fi

		mkdir -p "$(dirname "$out_path")"

		if [ -z "${seen_mock:-}" ]; then
			cp "$TMPDIR/header.txt" "$mock_path"
			seen_mock=true
		fi

		cat "$crd_path" >> "$out_path"
		cat "$crd_path" >> "$mock_path"
	done
done
