// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ConfigMapStatusApplyConfiguration represents a declarative configuration of the ConfigMapStatus type for use
// with apply.
//
// ConfigMapStatus defines the observed state of ConfigMapReplicaSet.
// This status reflects the current state of the managed ConfigMaps.
type ConfigMapStatusApplyConfiguration struct {
	// ReadyReplicas indicates the number of ConfigMaps that have been
	// successfully created and are currently managed by this controller.
	ReadyReplicas *int32 `json:"readyReplicas,omitempty"`
	// Conditions represent the latest available observations of the
	// ConfigMapReplicaSet's current state. This can be used to communicate
	// detailed status information to users and other controllers.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ConfigMapStatusApplyConfiguration constructs a declarative configuration of the ConfigMapStatus type for use with
// apply.
func ConfigMapStatus() *ConfigMapStatusApplyConfiguration {
	return &ConfigMapStatusApplyConfiguration{}
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *ConfigMapStatusApplyConfiguration) WithReadyReplicas(value int32) *ConfigMapStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ConfigMapStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ConfigMapStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
