// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NotaryStatusApplyConfiguration represents a declarative configuration of the NotaryStatus type for use
// with apply.
//
// NotaryStatus defines the observed state of Notary.
type NotaryStatusApplyConfiguration struct {
	// LastRecordedValue is the last value that was recorded in the ConfigMap
	LastRecordedValue *string `json:"lastRecordedValue,omitempty"`
	// ConfigMapStatus indicates the status of the ConfigMap operation
	ConfigMapStatus *string `json:"configMapStatus,omitempty"`
	// ChangeCount is the number of changes recorded so far
	ChangeCount *int `json:"changeCount,omitempty"`
}

// NotaryStatusApplyConfiguration constructs a declarative configuration of the NotaryStatus type for use with
// apply.
func NotaryStatus() *NotaryStatusApplyConfiguration {
	return &NotaryStatusApplyConfiguration{}
}

// WithLastRecordedValue sets the LastRecordedValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastRecordedValue field is set to the value of the last call.
func (b *NotaryStatusApplyConfiguration) WithLastRecordedValue(value string) *NotaryStatusApplyConfiguration {
	b.LastRecordedValue = &value
	return b
}

// WithConfigMapStatus sets the ConfigMapStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMapStatus field is set to the value of the last call.
func (b *NotaryStatusApplyConfiguration) WithConfigMapStatus(value string) *NotaryStatusApplyConfiguration {
	b.ConfigMapStatus = &value
	return b
}

// WithChangeCount sets the ChangeCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChangeCount field is set to the value of the last call.
func (b *NotaryStatusApplyConfiguration) WithChangeCount(value int) *NotaryStatusApplyConfiguration {
	b.ChangeCount = &value
	return b
}
