// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ComposeUpRequestSpecApplyConfiguration represents a declarative configuration of the ComposeUpRequestSpec type for use
// with apply.
//
// ComposeUpRequestSpec defines the identity of the `docker compose` project
// to bring up.
type ComposeUpRequestSpecApplyConfiguration struct {
	// Namespace is the container namespace; refers to a [ContainerNamespace]
	// object in the same Kubernetes namespace.  Immutable once created.
	//
	Namespace *string `json:"namespace,omitempty"`
	// Name is the compose project name.  Immutable once created.
	//
	Name *string `json:"name,omitempty"`
	// WorkingDir is the absolute path to the compose project directory on the
	// host (i.e. where the RDD process runs).  Used to look up any files needed.
	//
	WorkingDir *string `json:"workingDir,omitempty"`
	// Configs is the list of compose files used to create the project,
	// relative to workingDir.  It must be a descendent of workingDir.
	//
	Configs []string `json:"configs,omitempty"`
}

// ComposeUpRequestSpecApplyConfiguration constructs a declarative configuration of the ComposeUpRequestSpec type for use with
// apply.
func ComposeUpRequestSpec() *ComposeUpRequestSpecApplyConfiguration {
	return &ComposeUpRequestSpecApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ComposeUpRequestSpecApplyConfiguration) WithNamespace(value string) *ComposeUpRequestSpecApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ComposeUpRequestSpecApplyConfiguration) WithName(value string) *ComposeUpRequestSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithWorkingDir sets the WorkingDir field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkingDir field is set to the value of the last call.
func (b *ComposeUpRequestSpecApplyConfiguration) WithWorkingDir(value string) *ComposeUpRequestSpecApplyConfiguration {
	b.WorkingDir = &value
	return b
}

// WithConfigs adds the given value to the Configs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Configs field.
func (b *ComposeUpRequestSpecApplyConfiguration) WithConfigs(values ...string) *ComposeUpRequestSpecApplyConfiguration {
	for i := range values {
		b.Configs = append(b.Configs, values[i])
	}
	return b
}
