// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ComposeProjectStatusApplyConfiguration represents a declarative configuration of the ComposeProjectStatus type for use
// with apply.
//
// ComposeProjectStatus defines the observed state of a `docker compose` project.
type ComposeProjectStatusApplyConfiguration struct {
	// Namespace is the container namespace; refers to a [ContainerNamespace]
	// object in the same Kubernetes namespace.
	//
	Namespace *string `json:"namespace,omitempty"`
	// Name is the compose project name.
	//
	Name *string `json:"name,omitempty"`
	// WorkingDir is the absolute path to the compose project directory on the
	// host (i.e. relative to where the RDD process runs). May be unset.
	//
	WorkingDir *string `json:"workingDir,omitempty"`
	// Configs is the list of compose files used to create the project,
	// relative to WorkingDir. It is not guaranteed that this is sufficient to
	// recreate the project. May be unset.
	//
	Configs []string `json:"configs,omitempty"`
	// Containers tracks the containers that are part of the compose project.
	// The name is the metadata.name of the container object (i.e. the
	// container ID). The UID is also tracked.
	//
	Containers []ComposeProjectContainerApplyConfiguration `json:"containers,omitempty"`
	// Conditions represent the state of the compose project.
	// Known condition types include:
	//
	// - "HasMembers": The compose project has at least one member.
	//
	// The status of each condition is one of True, False, or Unknown.
	//
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ComposeProjectStatusApplyConfiguration constructs a declarative configuration of the ComposeProjectStatus type for use with
// apply.
func ComposeProjectStatus() *ComposeProjectStatusApplyConfiguration {
	return &ComposeProjectStatusApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ComposeProjectStatusApplyConfiguration) WithNamespace(value string) *ComposeProjectStatusApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ComposeProjectStatusApplyConfiguration) WithName(value string) *ComposeProjectStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithWorkingDir sets the WorkingDir field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkingDir field is set to the value of the last call.
func (b *ComposeProjectStatusApplyConfiguration) WithWorkingDir(value string) *ComposeProjectStatusApplyConfiguration {
	b.WorkingDir = &value
	return b
}

// WithConfigs adds the given value to the Configs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Configs field.
func (b *ComposeProjectStatusApplyConfiguration) WithConfigs(values ...string) *ComposeProjectStatusApplyConfiguration {
	for i := range values {
		b.Configs = append(b.Configs, values[i])
	}
	return b
}

// WithContainers adds the given value to the Containers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Containers field.
func (b *ComposeProjectStatusApplyConfiguration) WithContainers(values ...*ComposeProjectContainerApplyConfiguration) *ComposeProjectStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithContainers")
		}
		b.Containers = append(b.Containers, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ComposeProjectStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ComposeProjectStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
