// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// ComposeProjectContainerApplyConfiguration represents a declarative configuration of the ComposeProjectContainer type for use
// with apply.
//
// ComposeProjectContainer describes a single container that is part of a compose
// project.
type ComposeProjectContainerApplyConfiguration struct {
	// Name is the metadata.name of the container object (i.e. the container
	// ID).
	//
	Name *string `json:"name,omitempty"`
	// UID is the UID of the container object.
	//
	UID *types.UID `json:"uid,omitempty"`
}

// ComposeProjectContainerApplyConfiguration constructs a declarative configuration of the ComposeProjectContainer type for use with
// apply.
func ComposeProjectContainer() *ComposeProjectContainerApplyConfiguration {
	return &ComposeProjectContainerApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ComposeProjectContainerApplyConfiguration) WithName(value string) *ComposeProjectContainerApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ComposeProjectContainerApplyConfiguration) WithUID(value types.UID) *ComposeProjectContainerApplyConfiguration {
	b.UID = &value
	return b
}
