// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ComposeUpRequestStatusApplyConfiguration represents a declarative configuration of the ComposeUpRequestStatus type for use
// with apply.
//
// ComposeUpRequestStatus defines the observed state of a ComposeUpRequest.
type ComposeUpRequestStatusApplyConfiguration struct {
	// Conditions represent the state of the request.
	// Known condition types include:
	//
	// - "Settled": `docker compose up` has reached a terminal state (see the
	// Reason field for whether it succeeded or failed).
	// - "Failed": `docker compose up` failed.
	//
	// Failed can only be True if Settled is also True.  The status of each
	// condition is one of True, False, or Unknown.
	//
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ComposeUpRequestStatusApplyConfiguration constructs a declarative configuration of the ComposeUpRequestStatus type for use with
// apply.
func ComposeUpRequestStatus() *ComposeUpRequestStatusApplyConfiguration {
	return &ComposeUpRequestStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ComposeUpRequestStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ComposeUpRequestStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
