// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ContainerPortBindingApplyConfiguration represents a declarative configuration of the ContainerPortBinding type for use
// with apply.
//
// ContainerPortBinding describes one host port for the container to bind to.
type ContainerPortBindingApplyConfiguration struct {
	// HostIP is the host IP address that the container's port is mapped to.
	HostIP *string `json:"hostIP,omitempty"`
	// HostPort is the host port number that the container's port is mapped to.
	HostPort *string `json:"hostPort,omitempty"`
}

// ContainerPortBindingApplyConfiguration constructs a declarative configuration of the ContainerPortBinding type for use with
// apply.
func ContainerPortBinding() *ContainerPortBindingApplyConfiguration {
	return &ContainerPortBindingApplyConfiguration{}
}

// WithHostIP sets the HostIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostIP field is set to the value of the last call.
func (b *ContainerPortBindingApplyConfiguration) WithHostIP(value string) *ContainerPortBindingApplyConfiguration {
	b.HostIP = &value
	return b
}

// WithHostPort sets the HostPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostPort field is set to the value of the last call.
func (b *ContainerPortBindingApplyConfiguration) WithHostPort(value string) *ContainerPortBindingApplyConfiguration {
	b.HostPort = &value
	return b
}
