// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ImageStatusApplyConfiguration represents a declarative configuration of the ImageStatus type for use
// with apply.
//
// ImageStatus defines the observed state of the image.
type ImageStatusApplyConfiguration struct {
	// Namespace is the container namespace; refers to a `ContainerNamespace`
	// object in the same Kubernetes namespace.
	Namespace *string `json:"namespace,omitempty"`
	// ID is the image ID, as reported by the container runtime.
	ID *string `json:"id,omitempty"`
	// RepoTag is the tag of the image.  Images with multiple tags will have
	// multiple Image objects.  Images without tags will have this unset, but
	// only one Image object should exist in that case.
	RepoTag *string `json:"repoTag,omitempty"`
	// RepoDigests are the signed digests of the image.
	RepoDigests []string `json:"repoDigests,omitempty"`
	// CreatedAt is the time the image was created.
	CreatedAt *v1.Time `json:"createdAt,omitempty"`
	// Architecture associated with the image.
	Architecture *string `json:"architecture,omitempty"`
	// OS associated with the image.
	OS *string `json:"os,omitempty"`
	// Size of the image.
	Size *int64 `json:"size,omitempty"`
	// Labels of the image.
	Labels map[string]string `json:"labels,omitempty"`
	// Conditions represent the state of the image.
	// There are currently no defined condition types.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ImageStatusApplyConfiguration constructs a declarative configuration of the ImageStatus type for use with
// apply.
func ImageStatus() *ImageStatusApplyConfiguration {
	return &ImageStatusApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ImageStatusApplyConfiguration) WithNamespace(value string) *ImageStatusApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *ImageStatusApplyConfiguration) WithID(value string) *ImageStatusApplyConfiguration {
	b.ID = &value
	return b
}

// WithRepoTag sets the RepoTag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepoTag field is set to the value of the last call.
func (b *ImageStatusApplyConfiguration) WithRepoTag(value string) *ImageStatusApplyConfiguration {
	b.RepoTag = &value
	return b
}

// WithRepoDigests adds the given value to the RepoDigests field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RepoDigests field.
func (b *ImageStatusApplyConfiguration) WithRepoDigests(values ...string) *ImageStatusApplyConfiguration {
	for i := range values {
		b.RepoDigests = append(b.RepoDigests, values[i])
	}
	return b
}

// WithCreatedAt sets the CreatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreatedAt field is set to the value of the last call.
func (b *ImageStatusApplyConfiguration) WithCreatedAt(value v1.Time) *ImageStatusApplyConfiguration {
	b.CreatedAt = &value
	return b
}

// WithArchitecture sets the Architecture field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Architecture field is set to the value of the last call.
func (b *ImageStatusApplyConfiguration) WithArchitecture(value string) *ImageStatusApplyConfiguration {
	b.Architecture = &value
	return b
}

// WithOS sets the OS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OS field is set to the value of the last call.
func (b *ImageStatusApplyConfiguration) WithOS(value string) *ImageStatusApplyConfiguration {
	b.OS = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *ImageStatusApplyConfiguration) WithSize(value int64) *ImageStatusApplyConfiguration {
	b.Size = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ImageStatusApplyConfiguration) WithLabels(entries map[string]string) *ImageStatusApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ImageStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ImageStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
