// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VolumeStatusApplyConfiguration represents a declarative configuration of the VolumeStatus type for use
// with apply.
//
// VolumeStatus describes the configuration the volume was created with.
type VolumeStatusApplyConfiguration struct {
	// Name of the volume.
	Name *string `json:"name,omitempty"`
	// Namespace of the volume; refers to a `ContainerNamespace` object in the
	// same Kubernetes namespace.
	Namespace *string `json:"namespace,omitempty"`
	// CreatedAt is the time the volume was created.
	CreatedAt *v1.Time `json:"createdAt,omitempty"`
	// Driver the volume uses.
	Driver *string `json:"driver,omitempty"`
	// MountPoint is where on the host the volume is mounted.
	MountPoint *string `json:"mountpoint,omitempty"`
	// Labels for the volume.
	Labels map[string]string `json:"labels,omitempty"`
	// Scope of the volume.
	Scope *string `json:"scope,omitempty"`
	// Options for the volume driver.
	Options map[string]string `json:"options,omitempty"`
}

// VolumeStatusApplyConfiguration constructs a declarative configuration of the VolumeStatus type for use with
// apply.
func VolumeStatus() *VolumeStatusApplyConfiguration {
	return &VolumeStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithName(value string) *VolumeStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithNamespace(value string) *VolumeStatusApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithCreatedAt sets the CreatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreatedAt field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithCreatedAt(value v1.Time) *VolumeStatusApplyConfiguration {
	b.CreatedAt = &value
	return b
}

// WithDriver sets the Driver field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Driver field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithDriver(value string) *VolumeStatusApplyConfiguration {
	b.Driver = &value
	return b
}

// WithMountPoint sets the MountPoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MountPoint field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithMountPoint(value string) *VolumeStatusApplyConfiguration {
	b.MountPoint = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *VolumeStatusApplyConfiguration) WithLabels(entries map[string]string) *VolumeStatusApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithScope sets the Scope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scope field is set to the value of the last call.
func (b *VolumeStatusApplyConfiguration) WithScope(value string) *VolumeStatusApplyConfiguration {
	b.Scope = &value
	return b
}

// WithOptions puts the entries into the Options field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Options field,
// overwriting an existing map entries in Options field with the same key.
func (b *VolumeStatusApplyConfiguration) WithOptions(entries map[string]string) *VolumeStatusApplyConfiguration {
	if b.Options == nil && len(entries) > 0 {
		b.Options = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Options[k] = v
	}
	return b
}
