// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/extensions/v1alpha1"
	extensionsv1alpha1 "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/extensions/v1alpha1/applyconfiguration/extensions/v1alpha1"
	internal "github.com/rancher-sandbox/rancher-desktop-daemon/pkg/apis/extensions/v1alpha1/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=extensions.rancherdesktop.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("Extension"):
		return &extensionsv1alpha1.ExtensionApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ExtensionDashboardTabStatus"):
		return &extensionsv1alpha1.ExtensionDashboardTabStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ExtensionSpec"):
		return &extensionsv1alpha1.ExtensionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ExtensionStatus"):
		return &extensionsv1alpha1.ExtensionStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ExtensionUIStatus"):
		return &extensionsv1alpha1.ExtensionUIStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
