# This is a reusable workflow to determine if the current change requires an E2E
# run.  This is required because using [paths-ignored] directly means the whole
# workflow is skipped, but that means that it doesn't count as having run a
# required workflow.

# Usage:
#   jobs:
#     check-paths:
#        uses: ./.github/workflows/paths-ignore.yaml
#     do_thing:
#        needs: check-paths
#        if: needs.check-paths.outputs.should-run == 'true'
#        # Unfortunately, a string comparison is required.

name: Check for ignored paths

on:
  workflow_call:
    inputs:
      paths-ignore-globs:
        description: >
          Paths to ignore.  Should be in .gitignore format.  See
          https://git-scm.com/docs/gitignore
        type: string
        default: |
          /.github/actions/spelling/**
          /docs/**
          /rdd/docs/**
          **.md
    outputs:
      should-run:
        description: Whether other steps should run.
        value: ${{ jobs.check.outputs.should-run }}

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Set baseline result
      # This is needed in case the event type is not a pull_request.
      run: echo "SHOULD_RUN=true" >> "$GITHUB_ENV"
    - name: Determine paths to ignore
      if: github.event_name == 'pull_request'
      shell: cp {0} PATHS_IGNORE # Copy the input (text) to a file.
      working-directory: ${{ runner.temp }}
      run: ${{ inputs.paths-ignore-globs }}
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Check for differences
      if: github.event_name == 'pull_request'
      run: |
        MERGE_BASE=$(git merge-base $BASE $HEAD)
        # `git check-ignore` returns 1 if no files are ignored.  In that case,
        # as well as if it fails to run, treat it as success so we run dependent
        # jobs.
        if git diff --name-only $MERGE_BASE $HEAD \
          | { \
            git -c core.excludesFile=${{ runner.temp }}/PATHS_IGNORE \
              check-ignore --non-matching --no-index --verbose --stdin \
            || echo ":: git check-ignore failed with $?"; } \
          | grep --extended-regexp '^::'; then
          echo "Modified files found."
        else
          echo "No modified files found."
          echo "SHOULD_RUN=false" >> "$GITHUB_ENV"
        fi
      env:
        BASE: ${{ github.event.pull_request.base.sha }}
        HEAD: ${{ github.event.pull_request.head.sha }}
    - name: Set final output
      id: result
      run: echo "should-run=$SHOULD_RUN" >> "$GITHUB_OUTPUT"
    outputs:
      should-run: ${{ steps.result.outputs.should-run }}
