// Code generated by ./generate from github.com/containerd/nerdctl/v2@v2.0.3; DO NOT EDIT.

package nerdctlstub

// nerdctlVersion is the version the parse table was generated from.
const nerdctlVersion = "v2.0.3"

// commandSpecs describes every nerdctl command; the key is the
// space-separated command path, with "" for the root command.
var commandSpecs = map[string]commandSpec{
	"": {
		valueFlags:  []string{"--H", "--a", "--address", "--bridge-ip", "--cgroup-manager", "--cni-netconfpath", "--cni-path", "--data-root", "--host", "--host-gateway-ip", "--hosts-dir", "--n", "--namespace", "--snapshotter", "--storage-driver", "-H", "-a", "-n"},
		boolFlags:   []string{"--debug", "--debug-full", "--experimental", "--insecure-registry", "--kube-hide-dupe"},
		subcommands: []string{"apparmor", "attach", "build", "builder", "commit", "completion", "compose", "container", "cp", "create", "diff", "events", "exec", "help", "history", "image", "images", "info", "inspect", "ipfs", "kill", "load", "login", "logout", "logs", "namespace", "network", "pause", "port", "ps", "pull", "push", "rename", "restart", "rm", "rmi", "run", "save", "start", "stats", "stop", "system", "tag", "top", "unpause", "update", "version", "volume", "wait"},
	},
	"apparmor": {
		subcommands: []string{"inspect", "load", "ls", "unload"},
	},
	"apparmor inspect": {},
	"apparmor load":    {},
	"apparmor ls": {
		valueFlags: []string{"--format"},
		boolFlags:  []string{"--quiet", "-q"},
	},
	"apparmor unload": {},
	"builder": {
		subcommands: []string{"build", "debug", "prune"},
	},
	"builder build": {
		valueFlags: []string{"--add-host", "--allow", "--attest", "--build-arg", "--build-context", "--buildkit-host", "--cache-from", "--cache-to", "--file", "--iidfile", "--label", "--network", "--output", "--platform", "--progress", "--provenance", "--sbom", "--secret", "--ssh", "--tag", "--target", "-f", "-o", "-t"},
		boolFlags:  []string{"--no-cache", "--pull", "--quiet", "--rm", "-q"},
	},
	"builder debug": {
		valueFlags: []string{"--build-arg", "--file", "--image", "--secret", "--ssh", "--target", "-f"},
	},
	"builder prune": {
		valueFlags: []string{"--buildkit-host"},
		boolFlags:  []string{"--all", "--force", "-a", "-f"},
	},
	"completion": {
		subcommands: []string{"bash", "fish", "powershell", "zsh"},
	},
	"completion bash": {
		boolFlags: []string{"--no-descriptions"},
	},
	"completion fish": {
		boolFlags: []string{"--no-descriptions"},
	},
	"completion powershell": {
		boolFlags: []string{"--no-descriptions"},
	},
	"completion zsh": {
		boolFlags: []string{"--no-descriptions"},
	},
	"compose": {
		valueFlags:  []string{"--env-file", "--f", "--file", "--ipfs-address", "--profile", "--project-directory", "--project-name", "-f", "-p"},
		subcommands: []string{"build", "config", "cp", "create", "down", "exec", "images", "kill", "logs", "pause", "port", "ps", "pull", "push", "restart", "rm", "run", "start", "stop", "top", "unpause", "up", "version"},
	},
	"compose build": {
		valueFlags: []string{"--build-arg", "--progress"},
		boolFlags:  []string{"--no-cache"},
	},
	"compose config": {
		valueFlags: []string{"--hash"},
		boolFlags:  []string{"--quiet", "--services", "--volumes", "-q"},
	},
	"compose cp": {
		valueFlags: []string{"--index"},
		boolFlags:  []string{"--dry-run", "--follow-link", "-L"},
	},
	"compose create": {
		valueFlags: []string{"--pull"},
		boolFlags:  []string{"--build", "--force-recreate", "--no-build", "--no-recreate"},
	},
	"compose down": {
		boolFlags: []string{"--remove-orphans", "--volumes", "-v"},
	},
	"compose exec": {
		valueFlags:   []string{"--env", "--index", "--user", "--workdir", "-e", "-u", "-w"},
		boolFlags:    []string{"--detach", "--interactive", "--no-TTY", "--privileged", "--tty", "-T", "-d", "-i", "-t"},
		foreignFlags: true,
	},
	"compose images": {
		valueFlags: []string{"--format"},
		boolFlags:  []string{"--quiet", "-q"},
	},
	"compose kill": {
		valueFlags: []string{"--signal", "-s"},
	},
	"compose logs": {
		valueFlags: []string{"--tail"},
		boolFlags:  []string{"--follow", "--no-color", "--no-log-prefix", "--timestamps", "-f", "-t"},
	},
	"compose pause": {},
	"compose port": {
		valueFlags: []string{"--index", "--protocol"},
	},
	"compose ps": {
		valueFlags: []string{"--filter", "--format", "--status"},
		boolFlags:  []string{"--all", "--quiet", "--services", "-a", "-q"},
	},
	"compose pull": {
		boolFlags: []string{"--quiet", "-q"},
	},
	"compose push": {},
	"compose restart": {
		valueFlags: []string{"--timeout", "-t"},
	},
	"compose rm": {
		boolFlags: []string{"--force", "--stop", "--volumes", "-f", "-s", "-v"},
	},
	"compose run": {
		valueFlags:   []string{"--entrypoint", "--env", "--label", "--name", "--publish", "--user", "--volume", "--workdir", "-e", "-l", "-u", "-v", "-w"},
		boolFlags:    []string{"--build", "--detach", "--interactive", "--no-build", "--no-color", "--no-deps", "--no-log-prefix", "--quiet-pull", "--remove-orphans", "--rm", "--service-ports", "-d", "-i"},
		foreignFlags: true,
	},
	"compose start": {},
	"compose stop": {
		valueFlags: []string{"--timeout", "-t"},
	},
	"compose top":     {},
	"compose unpause": {},
	"compose up": {
		valueFlags: []string{"--pull", "--scale"},
		boolFlags:  []string{"--abort-on-container-exit", "--build", "--detach", "--force-recreate", "--ipfs", "--no-build", "--no-color", "--no-log-prefix", "--no-recreate", "--quiet-pull", "--remove-orphans", "-d"},
	},
	"compose version": {
		valueFlags: []string{"--format", "-f"},
		boolFlags:  []string{"--short"},
	},
	"container": {
		subcommands: []string{"attach", "commit", "cp", "create", "diff", "exec", "inspect", "kill", "logs", "ls", "pause", "port", "prune", "rename", "restart", "rm", "run", "start", "stats", "stop", "unpause", "update", "wait"},
	},
	"container attach": {
		valueFlags: []string{"--detach-keys"},
	},
	"container commit": {
		valueFlags: []string{"--author", "--change", "--message", "-a", "-c", "-m"},
		boolFlags:  []string{"--pause", "-p"},
	},
	"container cp": {
		boolFlags: []string{"--follow-link", "-L"},
	},
	"container create": {
		valueFlags:   []string{"--add-host", "--annotation", "--blkio-weight", "--cap-add", "--cap-drop", "--cgroup-conf", "--cgroup-parent", "--cgroupns", "--cidfile", "--cosign-certificate-identity", "--cosign-certificate-identity-regexp", "--cosign-certificate-oidc-issuer", "--cosign-certificate-oidc-issuer-regexp", "--cosign-key", "--cpu-period", "--cpu-quota", "--cpu-shares", "--cpus", "--cpuset-cpus", "--cpuset-mems", "--detach-keys", "--device", "--dns", "--dns-opt", "--dns-option", "--dns-search", "--entrypoint", "--env", "--env-file", "--gpus", "--group-add", "--hostname", "--init-binary", "--ip", "--ip6", "--ipc", "--ipfs-address", "--isolation", "--kernel-memory", "--label", "--label-file", "--log-driver", "--log-opt", "--mac-address", "--memory", "--memory-reservation", "--memory-swap", "--memory-swappiness", "--mount", "--name", "--net", "--network", "--oom-score-adj", "--pid", "--pidfile", "--pids-limit", "--platform", "--publish", "--pull", "--rdt-class", "--restart", "--runtime", "--security-opt", "--shm-size", "--stop-signal", "--stop-timeout", "--sysctl", "--systemd", "--tmpfs", "--ulimit", "--umask", "--user", "--uts", "--verify", "--volume", "--volumes-from", "--workdir", "-e", "-h", "-l", "-m", "-p", "-u", "-v", "-w"},
		boolFlags:    []string{"--help", "--init", "--interactive", "--oom-kill-disable", "--privileged", "--quiet", "--read-only", "--rm", "--rootfs", "--sig-proxy", "--tty", "-i", "-q", "-t"},
		foreignFlags: true,
	},
	"container diff": {},
	"container exec": {
		valueFlags:   []string{"--env", "--env-file", "--user", "--workdir", "-e", "-u", "-w"},
		boolFlags:    []string{"--detach", "--interactive", "--privileged", "--tty", "-d", "-i", "-t"},
		foreignFlags: true,
	},
	"container inspect": {
		valueFlags: []string{"--format", "--mode", "-f"},
		boolFlags:  []string{"--size", "-s"},
	},
	"container kill": {
		valueFlags: []string{"--signal", "-s"},
	},
	"container logs": {
		valueFlags: []string{"--since", "--tail", "--until", "-n"},
		boolFlags:  []string{"--follow", "--timestamps", "-f", "-t"},
	},
	"container ls": {
		valueFlags: []string{"--filter", "--format", "--last", "-f", "-n"},
		boolFlags:  []string{"--all", "--latest", "--no-trunc", "--quiet", "--size", "-a", "-l", "-q", "-s"},
	},
	"container pause": {},
	"container port":  {},
	"container prune": {
		boolFlags: []string{"--force", "-f"},
	},
	"container rename": {},
	"container restart": {
		valueFlags: []string{"--time", "-t"},
	},
	"container rm": {
		boolFlags: []string{"--force", "--volumes", "-f", "-v"},
	},
	"container run": {
		valueFlags:   []string{"--add-host", "--annotation", "--attach", "--blkio-weight", "--cap-add", "--cap-drop", "--cgroup-conf", "--cgroup-parent", "--cgroupns", "--cidfile", "--cosign-certificate-identity", "--cosign-certificate-identity-regexp", "--cosign-certificate-oidc-issuer", "--cosign-certificate-oidc-issuer-regexp", "--cosign-key", "--cpu-period", "--cpu-quota", "--cpu-shares", "--cpus", "--cpuset-cpus", "--cpuset-mems", "--detach-keys", "--device", "--dns", "--dns-opt", "--dns-option", "--dns-search", "--entrypoint", "--env", "--env-file", "--gpus", "--group-add", "--hostname", "--init-binary", "--ip", "--ip6", "--ipc", "--ipfs-address", "--isolation", "--kernel-memory", "--label", "--label-file", "--log-driver", "--log-opt", "--mac-address", "--memory", "--memory-reservation", "--memory-swap", "--memory-swappiness", "--mount", "--name", "--net", "--network", "--oom-score-adj", "--pid", "--pidfile", "--pids-limit", "--platform", "--publish", "--pull", "--rdt-class", "--restart", "--runtime", "--security-opt", "--shm-size", "--stop-signal", "--stop-timeout", "--sysctl", "--systemd", "--tmpfs", "--ulimit", "--umask", "--user", "--uts", "--verify", "--volume", "--volumes-from", "--workdir", "-a", "-e", "-h", "-l", "-m", "-p", "-u", "-v", "-w"},
		boolFlags:    []string{"--detach", "--help", "--init", "--interactive", "--oom-kill-disable", "--privileged", "--quiet", "--read-only", "--rm", "--rootfs", "--sig-proxy", "--tty", "-d", "-i", "-q", "-t"},
		foreignFlags: true,
	},
	"container start": {
		valueFlags: []string{"--detach-keys"},
		boolFlags:  []string{"--attach", "-a"},
	},
	"container stats": {
		valueFlags: []string{"--format"},
		boolFlags:  []string{"--all", "--no-stream", "--no-trunc", "-a"},
	},
	"container stop": {
		valueFlags: []string{"--time", "-t"},
	},
	"container unpause": {},
	"container update": {
		valueFlags: []string{"--blkio-weight", "--cpu-period", "--cpu-quota", "--cpu-shares", "--cpus", "--cpuset-cpus", "--cpuset-mems", "--kernel-memory", "--memory", "--memory-reservation", "--memory-swap", "--pids-limit", "--restart", "-m"},
	},
	"container wait": {},
	"help":           {},
	"image": {
		subcommands: []string{"build", "convert", "decrypt", "encrypt", "history", "inspect", "load", "ls", "prune", "pull", "push", "rm", "save", "tag"},
	},
	"image convert": {
		valueFlags: []string{"--estargz-chunk-size", "--estargz-compression-level", "--estargz-min-chunk-size", "--estargz-record-in", "--format", "--nydus-builder-path", "--nydus-compressor", "--nydus-prefetch-patterns", "--nydus-work-dir", "--overlaybd-dbstr", "--overlaybd-fs-type", "--platform", "--zstd-compression-level", "--zstdchunked-chunk-size", "--zstdchunked-compression-level", "--zstdchunked-record-in"},
		boolFlags:  []string{"--all-platforms", "--estargz", "--estargz-external-toc", "--estargz-keep-diff-id", "--nydus", "--oci", "--overlaybd", "--uncompress", "--zstd", "--zstdchunked"},
	},
	"image decrypt": {
		valueFlags: []string{"--dec-recipient", "--gpg-homedir", "--gpg-version", "--key", "--platform"},
		boolFlags:  []string{"--all-platforms"},
	},
	"image encrypt": {
		valueFlags: []string{"--dec-recipient", "--gpg-homedir", "--gpg-version", "--key", "--platform", "--recipient"},
		boolFlags:  []string{"--all-platforms"},
	},
	"image history": {
		valueFlags: []string{"--format", "-f"},
		boolFlags:  []string{"--human", "--no-trunc", "--quiet", "-H", "-q"},
	},
	"image inspect": {
		valueFlags: []string{"--format", "--mode", "--platform", "-f"},
	},
	"image load": {
		valueFlags: []string{"--input", "--platform", "-i"},
		boolFlags:  []string{"--all-platforms", "--quiet", "-q"},
	},
	"image ls": {
		valueFlags: []string{"--filter", "--format", "-f"},
		boolFlags:  []string{"--all", "--digests", "--names", "--no-trunc", "--quiet", "-a", "-q"},
	},
	"image prune": {
		valueFlags: []string{"--filter"},
		boolFlags:  []string{"--all", "--force", "-a", "-f"},
	},
	"image pull": {
		valueFlags: []string{"--cosign-certificate-identity", "--cosign-certificate-identity-regexp", "--cosign-certificate-oidc-issuer", "--cosign-certificate-oidc-issuer-regexp", "--cosign-key", "--ipfs-address", "--platform", "--soci-index-digest", "--unpack", "--verify"},
		boolFlags:  []string{"--all-platforms", "--quiet", "-q"},
	},
	"image push": {
		valueFlags: []string{"--cosign-key", "--ipfs-address", "--notation-key-name", "--platform", "--sign", "--soci-min-layer-size", "--soci-span-size"},
		boolFlags:  []string{"--all-platforms", "--allow-nondistributable-artifacts", "--estargz", "--ipfs-ensure-image", "--quiet", "-q"},
	},
	"image rm": {
		boolFlags: []string{"--async", "--force", "-f"},
	},
	"image save": {
		valueFlags: []string{"--output", "--platform", "-o"},
		boolFlags:  []string{"--all-platforms"},
	},
	"image tag": {},
	"images": {
		valueFlags: []string{"--filter", "--format", "-f"},
		boolFlags:  []string{"--all", "--digests", "--names", "--no-trunc", "--quiet", "-a", "-q"},
	},
	"inspect": {
		valueFlags: []string{"--format", "--mode", "--type", "-f"},
		boolFlags:  []string{"--size", "-s"},
	},
	"ipfs": {
		subcommands: []string{"registry"},
	},
	"ipfs registry": {
		subcommands: []string{"serve"},
	},
	"ipfs registry serve": {
		valueFlags: []string{"--ipfs-address", "--listen-registry", "--read-retry-num", "--read-timeout"},
	},
	"login": {
		valueFlags: []string{"--password", "--username", "-p", "-u"},
		boolFlags:  []string{"--password-stdin"},
	},
	"logout": {},
	"namespace": {
		subcommands: []string{"create", "inspect", "ls", "remove", "update"},
	},
	"namespace create": {
		valueFlags: []string{"--label", "-l"},
	},
	"namespace inspect": {
		valueFlags: []string{"--format", "-f"},
	},
	"namespace ls": {
		boolFlags: []string{"--quiet", "-q"},
	},
	"namespace remove": {
		boolFlags: []string{"--cgroup", "-c"},
	},
	"namespace update": {
		valueFlags: []string{"--label", "-l"},
	},
	"network": {
		subcommands: []string{"create", "inspect", "ls", "prune", "rm"},
	},
	"network create": {
		valueFlags: []string{"--driver", "--gateway", "--ip-range", "--ipam-driver", "--ipam-opt", "--label", "--opt", "--subnet", "-d", "-o"},
		boolFlags:  []string{"--ipv6"},
	},
	"network inspect": {
		valueFlags: []string{"--format", "--mode", "-f"},
	},
	"network ls": {
		valueFlags: []string{"--filter", "--format", "-f"},
		boolFlags:  []string{"--quiet", "-q"},
	},
	"network prune": {
		boolFlags: []string{"--force", "-f"},
	},
	"network rm": {},
	"ps": {
		valueFlags: []string{"--filter", "--format", "--last", "-f", "-n"},
		boolFlags:  []string{"--all", "--latest", "--no-trunc", "--quiet", "--size", "-a", "-l", "-q", "-s"},
	},
	"rmi": {
		boolFlags: []string{"--async", "--force", "-f"},
	},
	"system": {
		subcommands: []string{"events", "info", "prune"},
	},
	"system events": {
		valueFlags: []string{"--filter", "--format", "-f"},
	},
	"system info": {
		valueFlags: []string{"--format", "--mode", "-f"},
	},
	"system prune": {
		boolFlags: []string{"--all", "--force", "--volumes", "-a", "-f"},
	},
	"top": {},
	"version": {
		valueFlags: []string{"--format", "-f"},
	},
	"volume": {
		subcommands: []string{"create", "inspect", "ls", "prune", "rm"},
	},
	"volume create": {
		valueFlags: []string{"--label"},
	},
	"volume inspect": {
		valueFlags: []string{"--format", "-f"},
		boolFlags:  []string{"--size", "-s"},
	},
	"volume ls": {
		valueFlags: []string{"--filter", "--format", "-f"},
		boolFlags:  []string{"--quiet", "--size", "-q", "-s"},
	},
	"volume prune": {
		boolFlags: []string{"--all", "--force", "-a", "-f"},
	},
	"volume rm": {
		boolFlags: []string{"--force", "-f"},
	},
}

// commandAliases maps every alias path to its canonical command path.
var commandAliases = map[string]string{
	"attach":      "container attach",
	"build":       "builder build",
	"commit":      "container commit",
	"cp":          "container cp",
	"create":      "container create",
	"diff":        "container diff",
	"events":      "system events",
	"exec":        "container exec",
	"history":     "image history",
	"image build": "builder build",
	"info":        "system info",
	"kill":        "container kill",
	"load":        "image load",
	"logs":        "container logs",
	"pause":       "container pause",
	"port":        "container port",
	"pull":        "image pull",
	"push":        "image push",
	"rename":      "container rename",
	"restart":     "container restart",
	"rm":          "container rm",
	"run":         "container run",
	"save":        "image save",
	"start":       "container start",
	"stats":       "container stats",
	"stop":        "container stop",
	"tag":         "image tag",
	"unpause":     "container unpause",
	"update":      "container update",
	"wait":        "container wait",
}
