// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LimaVMSpecApplyConfiguration represents a declarative configuration of the LimaVMSpec type for use
// with apply.
//
// LimaVMSpec defines the desired state of LimaVM.
type LimaVMSpecApplyConfiguration struct {
	// templateRef is a reference to a ConfigMap containing the VM template.
	// This field is immutable after creation.
	TemplateRef *TemplateReferenceApplyConfiguration `json:"templateRef,omitempty"`
	// running specifies whether the VM should be running
	Running *bool `json:"running,omitempty"`
}

// LimaVMSpecApplyConfiguration constructs a declarative configuration of the LimaVMSpec type for use with
// apply.
func LimaVMSpec() *LimaVMSpecApplyConfiguration {
	return &LimaVMSpecApplyConfiguration{}
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *LimaVMSpecApplyConfiguration) WithTemplateRef(value *TemplateReferenceApplyConfiguration) *LimaVMSpecApplyConfiguration {
	b.TemplateRef = value
	return b
}

// WithRunning sets the Running field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Running field is set to the value of the last call.
func (b *LimaVMSpecApplyConfiguration) WithRunning(value bool) *LimaVMSpecApplyConfiguration {
	b.Running = &value
	return b
}
