// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// LimaVMStatusApplyConfiguration represents a declarative configuration of the LimaVMStatus type for use
// with apply.
//
// LimaVMStatus defines the observed state of LimaVM.
type LimaVMStatusApplyConfiguration struct {
	// conditions represent the current state of the LimaVM resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// templateConfigMap is the name of the ConfigMap containing the validated template.
	// This ConfigMap is created and managed by the controller and is owned by this LimaVM resource.
	// An admission controller validates any updates to the ConfigMap.
	// This field is informational - internal code should use GetTemplateConfigMapName() instead.
	TemplateConfigMap *string `json:"templateConfigMap,omitempty"`
	// restartNeeded indicates a restart has been requested but not yet executed.
	// Set by the reconciler when it processes a restartRequested annotation or
	// detects a template change on a running instance. Cleared when the restart
	// completes or the instance is already stopped.
	RestartNeeded *bool `json:"restartNeeded,omitempty"`
	// restartCount tracks how many times the instance has reached the Running state.
	// Incremented each time the controller sets Running=True/Started.
	RestartCount *int32 `json:"restartCount,omitempty"`
}

// LimaVMStatusApplyConfiguration constructs a declarative configuration of the LimaVMStatus type for use with
// apply.
func LimaVMStatus() *LimaVMStatusApplyConfiguration {
	return &LimaVMStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *LimaVMStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *LimaVMStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithTemplateConfigMap sets the TemplateConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateConfigMap field is set to the value of the last call.
func (b *LimaVMStatusApplyConfiguration) WithTemplateConfigMap(value string) *LimaVMStatusApplyConfiguration {
	b.TemplateConfigMap = &value
	return b
}

// WithRestartNeeded sets the RestartNeeded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartNeeded field is set to the value of the last call.
func (b *LimaVMStatusApplyConfiguration) WithRestartNeeded(value bool) *LimaVMStatusApplyConfiguration {
	b.RestartNeeded = &value
	return b
}

// WithRestartCount sets the RestartCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestartCount field is set to the value of the last call.
func (b *LimaVMStatusApplyConfiguration) WithRestartCount(value int32) *LimaVMStatusApplyConfiguration {
	b.RestartCount = &value
	return b
}
